"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type ManagerData = { activeCycle: { id: number; name: string; phase: string; startDate: string; endDate: string } | null; pendingApprovals: number; myPendingReviews: number; directReports: { id: number; firstName: string; lastName: string; jobTitle: string | null; department: { name: string }; submitted: number; total: number; complete: boolean }[]; teamReviewTotal: number; teamReviewSubmitted: number; teamScores: { employeeId: number; name: string; score: number | null; cycleName: string | null }[]; refreshedAt: string };

function Metric({ label, value, detail, colour }: { label: string; value: string | number; detail: string; colour: string }) { return <div className="bg-white rounded-2xl border border-gray-100 p-5 relative overflow-hidden"><div className={`absolute inset-x-0 top-0 h-1 ${colour}`} /><p className="text-[11px] uppercase tracking-[.16em] font-bold text-gray-400">{label}</p><p className="text-3xl font-black text-gray-900 mt-3 leading-none">{value}</p><p className="text-xs text-gray-500 mt-2">{detail}</p></div>; }

export function ManagerDashboard({ name }: { name: string }) {
  const [data, setData] = useState<ManagerData | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async (quiet = false) => { if (quiet) setRefreshing(true); else setLoading(true); try { const response = await fetch("/api/dashboard/manager", { cache: "no-store" }); if (!response.ok) throw new Error("Unable to load the manager dashboard"); setData(await response.json() as ManagerData); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load the manager dashboard"); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { load(); const interval = window.setInterval(() => load(true), 15000); const onFocus = () => load(true); window.addEventListener("focus", onFocus); return () => { window.clearInterval(interval); window.removeEventListener("focus", onFocus); }; }, [load]);
  if (loading || !data) return <div className="bg-white rounded-2xl border border-gray-200 p-12 text-center text-sm text-gray-400">Loading your team dashboard…</div>;
  if (error) return <div className="bg-red-50 border border-red-200 rounded-2xl p-6 text-sm text-red-700"><strong>Dashboard unavailable.</strong><p className="mt-1">{error}</p><button onClick={() => load()} className="mt-4 px-3 py-2 rounded-lg bg-red-700 text-white text-xs font-bold">Try again</button></div>;
  const firstName = name?.split(" ")[0] ?? "Manager"; const total = data.teamReviewTotal; const submitted = data.teamReviewSubmitted; const progress = total ? Math.round(submitted / total * 100) : 0; const blockers = data.directReports.filter((employee) => employee.total > 0 && !employee.complete).sort((a, b) => a.submitted / a.total - b.submitted / b.total).slice(0, 3);
  return <div className="space-y-6"><div className="rounded-2xl bg-[#0f1f3d] p-7 text-white relative overflow-hidden"><div className="absolute -right-12 -top-16 w-64 h-64 rounded-full bg-white opacity-5" /><div className="relative flex items-start justify-between gap-5"><div><p className="text-blue-300 text-sm font-medium mb-1">Manager dashboard</p><h1 className="text-2xl font-black tracking-tight">Hi, {firstName}</h1><p className="text-blue-200 text-sm mt-1.5">{data.activeCycle ? `${data.activeCycle.name} · ${data.activeCycle.phase} phase` : "No active review cycle"}</p></div><div className="text-right"><p className="text-blue-300 text-[11px] uppercase tracking-widest font-bold">Team size</p><p className="text-4xl font-black mt-1">{data.directReports.length}</p><p className="text-blue-200 text-xs">direct reports</p><p className="text-xs text-blue-200 mt-3"><span className={`inline-block w-2 h-2 rounded-full mr-1 ${refreshing ? "bg-blue-300 animate-pulse" : "bg-emerald-300"}`} />{refreshing ? "Updating" : "Live"}</p></div></div></div>
    {(data.pendingApprovals > 0 || data.myPendingReviews > 0) && <div className="grid md:grid-cols-2 gap-4">{data.pendingApprovals > 0 && <Link href="/approvals" className="bg-amber-50 border border-amber-200 rounded-2xl p-5 hover:bg-amber-100 transition"><p className="text-sm font-bold text-amber-900">{data.pendingApprovals} approval{data.pendingApprovals === 1 ? "" : "s"} waiting</p><p className="text-xs text-amber-700 mt-1">Review your team&apos;s nominations.</p></Link>}{data.myPendingReviews > 0 && <Link href="/reviews" className="bg-purple-50 border border-purple-200 rounded-2xl p-5 hover:bg-purple-100 transition"><p className="text-sm font-bold text-purple-900">{data.myPendingReviews} review{data.myPendingReviews === 1 ? "" : "s"} to complete</p><p className="text-xs text-purple-700 mt-1">Submit your assigned feedback.</p></Link>}</div>}
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Metric label="Approval workload" value={data.pendingApprovals} detail="team nominations pending" colour="bg-amber-500" /><Metric label="Team progress" value={`${progress}%`} detail={`${submitted} of ${total} reviews submitted`} colour="bg-emerald-500" /><Metric label="My reviews" value={data.myPendingReviews} detail="assignments to complete" colour="bg-purple-500" /><Metric label="Team members" value={data.directReports.length} detail="active direct reports" colour="bg-blue-500" /></div>
    <div className="grid lg:grid-cols-3 gap-6"><div className="lg:col-span-2 bg-white rounded-2xl border border-gray-100 p-6"><div className="flex items-center justify-between mb-5"><div><h2 className="text-base font-bold text-gray-900">Team review progress</h2><p className="text-xs text-gray-500 mt-1">Spot incomplete work before the cycle deadline.</p></div><span className="text-2xl font-black text-gray-900">{progress}%</span></div><div className="h-3 rounded-full bg-gray-100 overflow-hidden mb-5"><div className="h-full rounded-full bg-emerald-500 transition-all duration-500" style={{ width: `${progress}%` }} /></div><div className="space-y-3">{data.directReports.slice(0, 5).map((employee) => <div key={employee.id} className="flex items-center gap-3"><div className="w-8 h-8 rounded-full bg-[#0f1f3d] text-white flex items-center justify-center text-xs font-bold">{employee.firstName.charAt(0)}</div><div className="flex-1 min-w-0"><p className="text-sm font-semibold text-gray-900 truncate">{employee.firstName} {employee.lastName}</p><p className="text-xs text-gray-400">{employee.submitted}/{employee.total || 0} reviews submitted</p></div><div className="w-24 h-2 rounded-full bg-gray-100 overflow-hidden"><div className="h-full bg-blue-500 rounded-full" style={{ width: `${employee.total ? employee.submitted / employee.total * 100 : 0}%` }} /></div></div>)}</div>{data.directReports.length > 5 && <Link href="/manager/results" className="block text-xs font-bold text-[#0f1f3d] mt-5 hover:underline">View full team results →</Link>}</div><div className="bg-white rounded-2xl border border-gray-100 p-6"><h2 className="text-base font-bold text-gray-900">Bottlenecks</h2><p className="text-xs text-gray-500 mt-1 mb-5">People with the most review work outstanding.</p>{blockers.length ? blockers.map((employee) => <div key={employee.id} className="mb-4"><div className="flex justify-between gap-3 text-sm"><span className="font-semibold text-gray-800 truncate">{employee.firstName} {employee.lastName}</span><span className="text-amber-700 font-bold">{employee.total - employee.submitted} left</span></div><div className="h-2 rounded-full bg-gray-100 mt-2 overflow-hidden"><div className="h-full bg-amber-400 rounded-full" style={{ width: `${employee.total ? employee.submitted / employee.total * 100 : 0}%` }} /></div></div>) : <p className="text-sm text-emerald-700 bg-emerald-50 rounded-lg p-3">No team review bottlenecks detected.</p>}<Link href="/approvals" className="block text-xs font-bold text-[#0f1f3d] mt-5 hover:underline">Open approvals →</Link></div></div>
    <div className="bg-white rounded-2xl border border-gray-100 p-6"><div className="flex items-center justify-between mb-5"><div><h2 className="text-base font-bold text-gray-900">Team performance snapshot</h2><p className="text-xs text-gray-500 mt-1">Latest released overall scores. Detailed feedback remains in Team Results.</p></div><Link href="/manager/results" className="text-xs font-bold text-[#0f1f3d] hover:underline">Team results →</Link></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{data.teamScores.slice(0, 8).map((employee) => <div key={employee.employeeId} className="border border-gray-100 rounded-xl p-4"><p className="text-sm font-semibold text-gray-900 truncate">{employee.name}</p><p className="text-2xl font-black text-[#0f1f3d] mt-2">{employee.score === null ? "—" : `${employee.score.toFixed(2)}/5`}</p><p className="text-[11px] text-gray-400 mt-1 truncate">{employee.cycleName ?? "No released result"}</p></div>)}</div></div>
  </div>;
}
