export type PdfBarRow = {
  label: string;
  value: number | null;
};

export type PdfReportInput = {
  title: string;
  cycleName: string;
  orgOverall: number | null;
  narrative: string;
  departments: PdfBarRow[];
  criteria: PdfBarRow[];
};

export function sanitizeFileName(value: string, fallback = "download") {
  const clean = value
    .replace(/[<>:"/\\|?*\x00-\x1f]/g, "-")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return clean || fallback;
}

export function downloadBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

export function downloadTextFile(content: string, fileName: string, type: string) {
  downloadBlob(new Blob([content], { type }), fileName);
}

export function escapeCsvCell(value: string | number | null | undefined) {
  if (value === null || value === undefined) return "";
  const text = String(value);
  return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

export function htmlToPlainText(html: string) {
  if (typeof document === "undefined") return html.replace(/<[^>]+>/g, " ");
  const node = document.createElement("div");
  node.innerHTML = html;
  return node.textContent?.replace(/\s+/g, " ").trim() ?? "";
}

function pdfText(value: string) {
  return value
    .replace(/[^\x09\x0a\x0d\x20-\x7e]/g, " ")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

function wrapText(text: string, maxChars: number) {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length > maxChars && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
  }

  if (current) lines.push(current);
  return lines;
}

export function createPulse360ReportPdf(input: PdfReportInput) {
  const pageWidth = 595;
  const pageHeight = 842;
  const margin = 48;
  const contentWidth = pageWidth - margin * 2;
  const pages: string[][] = [[]];
  let pageIndex = 0;
  let y = pageHeight - margin;

  function ops() {
    return pages[pageIndex];
  }

  function addPage() {
    pages.push([]);
    pageIndex += 1;
    y = pageHeight - margin;
  }

  function ensure(space: number) {
    if (y - space < margin) addPage();
  }

  function text(value: string, x: number, size = 10, color = "0.10 0.12 0.16") {
    ops().push(`${color} rg BT /F1 ${size} Tf ${x} ${y} Td (${pdfText(value)}) Tj ET`);
  }

  function line(value: string, size = 10, gap = 14, color = "0.10 0.12 0.16") {
    ensure(gap + 4);
    text(value, margin, size, color);
    y -= gap;
  }

  function heading(value: string) {
    ensure(28);
    text(value, margin, 14, "0.06 0.12 0.24");
    y -= 22;
  }

  function paragraph(value: string) {
    for (const wrapped of wrapText(value, 92).slice(0, 12)) {
      line(wrapped, 9, 13, "0.22 0.25 0.30");
    }
  }

  function barRows(title: string, rows: PdfBarRow[]) {
    heading(title);
    const filtered = rows.filter((row) => row.value !== null).slice(0, 12);
    if (filtered.length === 0) {
      line("No data available.", 9, 16, "0.45 0.49 0.56");
      return;
    }

    for (const row of filtered) {
      ensure(24);
      const value = Number(row.value ?? 0);
      const width = Math.max(3, Math.min(contentWidth - 160, (value / 5) * (contentWidth - 160)));
      text(row.label.slice(0, 34), margin, 9, "0.18 0.22 0.28");
      ops().push(`0.90 0.92 0.95 rg ${margin + 180} ${y - 4} ${contentWidth - 220} 8 re f`);
      ops().push(`0.23 0.51 0.82 rg ${margin + 180} ${y - 4} ${width} 8 re f`);
      text(value.toFixed(2), pageWidth - margin - 36, 9, "0.06 0.12 0.24");
      y -= 18;
    }
    y -= 6;
  }

  ops().push("0.06 0.12 0.24 rg 0 792 595 50 re f");
  y = 812;
  text("Pulse360 Executive Performance Report", margin, 18, "1 1 1");
  y -= 26;
  text(input.title, margin, 11, "0.82 0.89 1");
  y = 748;

  line(`Cycle: ${input.cycleName}`, 11, 18);
  line(`Organisation overall: ${input.orgOverall !== null ? input.orgOverall.toFixed(2) : "No score"} / 5`, 11, 24);

  heading("Executive Narrative");
  paragraph(input.narrative || "No narrative was provided.");
  y -= 8;

  barRows("Department Dashboard", input.departments);
  barRows("Criteria Dashboard", input.criteria);

  ensure(40);
  ops().push(`0.88 0.90 0.94 rg ${margin} ${y - 8} ${contentWidth} 1 re f`);
  y -= 24;
  line("Generated by Pulse360. Reviewed by HR before download.", 8, 10, "0.45 0.49 0.56");

  const objects: string[] = [];
  const pageObjectIds: number[] = [];
  objects.push("<< /Type /Catalog /Pages 2 0 R >>");
  objects.push("");
  objects.push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");

  for (const pageOps of pages) {
    const content = pageOps.join("\n");
    objects.push(`<< /Length ${content.length} >>\nstream\n${content}\nendstream`);
    pageObjectIds.push(objects.length + 1);
    objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 3 0 R >> >> /Contents ${objects.length - 1} 0 R >>`);
  }

  objects[1] = `<< /Type /Pages /Kids [${pageObjectIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageObjectIds.length} >>`;

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xref = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;

  return new Blob([pdf], { type: "application/pdf" });
}
