import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { NextRequest, NextResponse } from "next/server";
import fs from "fs";
import path from "path";

// POST /api/mcp/generate-report
// Saves an approved HTML report to the user's specified path.
// This is the server-side implementation of the MCP generate_pdf_report tool.
// Invoked ONLY after the user has reviewed and approved the report in the UI (human-in-the-loop).
export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  if ((session.user as any).role !== "HR_ADMIN") return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const { outputPath, htmlContent, reportTitle } = await req.json();
  if (!outputPath || !htmlContent || !reportTitle) {
    return NextResponse.json({ error: "outputPath, htmlContent, reportTitle required" }, { status: 400 });
  }

  try {
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${String(reportTitle).replace(/</g, "&lt;")}</title>
  <style>
    @media print { body { margin: 0; } .no-print { display: none; } }
    body { font-family: system-ui, -apple-system, sans-serif; font-size: 14px; color: #1f2328; background: #fff; }
  </style>
</head>
<body>
<div class="no-print" style="background:#0f1f3d;color:#fff;padding:10px 20px;font-size:13px">
  Pulse360 Report — <strong>${String(reportTitle).replace(/</g, "&lt;")}</strong>
  &nbsp;·&nbsp;<a href="javascript:window.print()" style="color:#93c5fd;text-decoration:underline">Print / Save as PDF</a>
</div>
${htmlContent}
<div style="border-top:1px solid #e5e7eb;padding:12px 20px;margin-top:24px;font-size:11px;color:#9ca3af;text-align:center">
  Generated by Pulse360 · Human-reviewed before export
</div>
</body>
</html>`;

    fs.writeFileSync(outputPath, fullHtml, "utf-8");
    return NextResponse.json({ ok: true, path: outputPath });
  } catch (err) {
    console.error("generate-report write error:", err);
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}
